"""THE REPLAY HARNESS — SPEC_settled_measurement.md §46/A1-A2, §42.0.

⭐⭐ Every "ten runs bit-identical" claim in §40-§48 was computed OUTSIDE the evaluator, in a scratch script.
This is what makes those claims the tree's rather than a spreadsheet's: it drives the REAL
`ClearingEvaluator` over the rows of every monitored run the archive holds, and asserts the answer.

⚠ THE FIXTURE PINS *RECOMPUTED* ANSWERS, NOT THE PRINTED ONES (§45/RD9). Seven of the sixteen archived
records were produced by `clearing-1.0`, the rule §29 replaced — asserting against what those PDFs printed
would encode the OLD rule as the expectation. `recordedAnswer` is carried alongside for context and is
deliberately NOT asserted.

⛔ The test never reads a PDF. `tests/data/monitor_replay.json` is generated by hand from the report PDFs
(see its `source` field); regenerating it is a deliberate act, which is the point — the fixture is the
contract, and a change to it must appear in a diff.
"""
import json
import os

import pytest

from sciens.spectracs.plugin_sdk.acquisition.MonitorDecision import MonitorDecision
from sciens.spectracs.plugin_sdk.acquisition.MonitorRow import MonitorRow
from sciens.spectracs.plugins.dev.DevSpectralPlugin import ClearingEvaluator, DevSpectralPlugin

FIXTURE = os.path.join(os.path.dirname(__file__), "data", "monitor_replay.json")
_VALUE_KEYS = ("qPercent", "soret", "valley", "qBand")


def loadRuns():
    with open(FIXTURE) as handle:
        return json.load(handle)["runs"]


def rowsOf(run):
    """⭐ D1/§46-D4 — the fixture carries RAW band means, so the ceiling is applied here exactly as
    `DevSpectralPlugin.monitorMetrics()` applies it at capture time. ⛔ The constant is READ from the plugin
    rather than pasted, so the two cannot drift: a fixture that kept its own 1.5 would keep passing after
    someone re-derived the real one."""
    ceiling = DevSpectralPlugin.MONITOR_SORET_CEILING
    rows = []
    for raw in run["rows"]:
        if raw.get("soret") is not None and raw["soret"] > ceiling:
            rows.append(MonitorRow(t=raw["t"], frameIndex=raw["frameIndex"], n=raw["n"],
                                   nAccepted=raw["nAccepted"], values={"tooDark": 1.0, "soret": raw["soret"]},
                                   provisional=bool(raw["provisional"]),
                                   isDecisionRow=bool(raw["isDecisionRow"])))
            continue
        values = {key: raw[key] for key in _VALUE_KEYS if raw.get(key) is not None}
        rows.append(MonitorRow(t=raw["t"], frameIndex=raw["frameIndex"], n=raw["n"],
                               nAccepted=raw["nAccepted"], values=values,
                               provisional=bool(raw["provisional"]),
                               isDecisionRow=bool(raw["isDecisionRow"])))
    return rows


def replay(run, mode=None):
    """Drive the real evaluator over a run's rows exactly as `MonitorEngine` would.

    ⭐ Mirrors `MonitorEngine.offer()` -> `__applyDecision()` -> the §14.6 latch, and then `__finish()` ->
    `finalize()` (§43/RD1). Returns what the record would carry.
    """
    evaluator = ClearingEvaluator(None, None, mode, windowFrames=run.get("windowFrames") or 60)
    rows = rowsOf(run)
    seen, answer, stopped = [], None, False
    for row in rows:
        seen.append(row)
        if stopped or not row.isDecisionRow:
            continue
        decision = evaluator.decide(seen) or MonitorDecision.carryOn()
        if decision.promote and answer is None:
            answer = _answerOf(decision, row, "gate")
        if decision.stop:
            stopped = True
    final = getattr(evaluator, "finalize", None)
    if final is not None:
        decision = final(list(seen))
        if decision is not None and decision.promote:
            answer = _answerOf(decision, seen[-1], "final", gateAnswer=answer)
        elif decision is not None and getattr(decision, "withdraw", False):
            # ⛔ §40.4 — a finalize that REFUSES takes the gate's answer with it, or run 003 keeps the
            # 8.450 the end-of-run read has just judged unsound.
            answer = {"value": None, "t": None, "readAs": None, "branch": None, "readPhase": "final",
                      "outcome": getattr(decision.outcome, "value", decision.outcome),
                      "gateAnswer": answer and answer["value"]}
    return answer


def _answerOf(decision, row, readPhase, gateAnswer=None):
    winner = decision.promoteRow if decision.promoteRow is not None else row
    value = decision.answer if decision.answer is not None else winner.get("qPercent")
    answer = {"value": value, "t": winner.t, "readAs": decision.readAs, "branch": decision.branch,
              "readPhase": readPhase, "outcome": getattr(decision.outcome, "value", decision.outcome)}
    if gateAnswer is not None:
        answer["gateAnswer"] = gateAnswer["value"]
    return answer


# --------------------------------------------------------------------------------------------------

def test_the_fixture_covers_every_monitored_run_the_archive_holds():
    runs = loadRuns()
    assert len(runs) == 16, "the archive holds sixteen monitored runs; the fixture has %d" % len(runs)
    assert sum(len(run["rows"]) for run in runs) == 379


@pytest.mark.parametrize("run", loadRuns(), ids=lambda run: run["id"])
def test_the_real_evaluator_reproduces_the_pinned_answer(run):
    """⭐ THE point of the harness. A change to any read rule shows up here, run by run, as a diff."""
    answer = replay(run)
    expected = run["expected"]
    if expected["value"] is None:
        assert answer is None or answer["value"] is None, \
            "%s: expected NO answer, got %r" % (run["id"], answer and answer["value"])
        return
    assert answer is not None, "%s: expected %.4f, got no answer at all" % (run["id"], expected["value"])
    assert answer["value"] == pytest.approx(expected["value"], abs=1e-6), \
        "%s: %.4f -> %.4f" % (run["id"], expected["value"], answer["value"])
    assert answer["readAs"] == expected["readAs"]
    assert answer["branch"] == expected["branch"]


@pytest.mark.parametrize("run", loadRuns(), ids=lambda run: run["id"])
def test_every_answer_comes_from_the_END_OF_RUN_read(run):
    """§45/M2 — a core/plugin repo skew fails SILENTLY: the probe finds no `finalize`, the run reverts to
    the gate-time answer, and nothing says so. `readPhase` is the detector, so the harness asserts it."""
    answer = replay(run)
    if answer is None:
        return
    assert answer["readPhase"] == "final", \
        "%s read at the GATE — either finalize is missing (a repo skew) or it declined" % run["id"]


def test_the_absorbance_CEILING_drops_exactly_the_rows_the_archive_says_it_should():
    """§32.4 / §46-D4 — nine of twelve runs untouched; 006L and Billa 001 lose opening rows with no change of
    answer; Billa 003 loses its first 21, which is the whole dark-floor stretch that produced 8.450."""
    dropped = {run["id"]: sum(1 for row in rowsOf(run) if row.get("tooDark")) for run in loadRuns()}
    assert dropped == {"20260817LigitschA/001": 0, "20260817LigitschA/002": 0, "20260817LigitschA/003": 0,
                       "20260817LigitschA/004": 0, "20260817LigitschA/005": 0, "20260817LigitschA/006": 5,
                       "20260817LigitschA/007": 0, "20260818A/001": 0, "20260819/001": 0,
                       "20280819BillaClever/001": 2, "20280819BillaClever/002": 0,
                       "20280819BillaClever/003": 21, "20280819BillaClever/004": 0,
                       "20280819BillaClever/005": 6, "20280819BillaClever/006": 1,
                       "20280819BillaClever/007": 0}, \
        "the ceiling touches five runs; every other answer must be reached without it"
    # ⭐ AND IT COSTS THOSE FIVE NOTHING BUT 003: the pinned answers above are unchanged for 006L, Billa
    # 001, 005 and 006 — the dropped rows are all in the opening ramp, before anything could be read.
